version: "3.5"

services:
  server:
    image: golang:1.17-stretch
    ports:
      - 8888:8888
    volumes:
      - ./:/go/src/app
      - ./data/go/pkg/mod:/go/pkg/mod
      - ./data/go/bin:/go/bin
    environment:
      - GO111MODULE=on
    working_dir: /go/src/app
    tty: true